# cloudbuild.yaml

substitutions:
  _MODEL_PATH: "minealsan-dsr/fruit-classifier/resnet18-fruit-best:v1"

# When using a custom service account, you must opt out of the default GCS logs bucket
options:
  logging: CLOUD_LOGGING_ONLY
  
availableSecrets:
  secretManager:
  - versionName: "projects/my-fruit-api/secrets/WANDB_API_KEY/versions/latest"
    env: "WANDB_API_KEY"

steps:
# 1) Build & push
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - "gcr.io/$PROJECT_ID/fruit-classifier:$SHORT_SHA"
    - -t
    - "gcr.io/$PROJECT_ID/fruit-classifier:latest"
    - -f
    - demo/Dockerfile
    - demo/

# 2) Deploy to Cloud Run (secret is available automatically)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      gcloud run deploy fruit-classifier \
        --image gcr.io/$PROJECT_ID/fruit-classifier:$SHORT_SHA \
        --region europe-west1 \
        --platform managed \
        --allow-unauthenticated \
        --port 8080 \
        --set-env-vars MODEL_PATH=$_MODEL_PATH,WANDB_API_KEY=$WANDB_API_KEY

images:
  - "gcr.io/$PROJECT_ID/fruit-classifier:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/fruit-classifier:latest"
